##
## EPITECH PROJECT, 2025
## makefile
## File description:
## build libhashtable.a
##

NAME    = libshell.a

all: $(NAME)

$(NAME):
	ar rc $(NAME)

clean:
	rm -f $(NAME)

fclean: clean
	rm -f $(NAME)

re: fclean all
