#!/bin/python3

import sys
import os
import numpy as np
from scipy.io import wavfile
import wave

def print_help():
    print("USAGE")
    print("    ./stone_analysis [--analyze | -a] IN_FILE N")
    print("                     [--cypher | -c] IN_FILE OUT_FILE MESSAGE")
    print("                     [--decypher | -d] IN_FILE\n")
    print("DESCRIPTION")
    print("    IN_FILE An audio file to be analyzed")
    print("    OUT_FILE Output audio file of the cypher mode")
    print("    MESSAGE The message to hide in the audio file")
    print("    N Number of top frequencies to display")
    
def check_extension(file_args):
    _, file_extension = os.path.splitext(file_args)
    if (file_extension != ".wav"):
        sys.exit(84)
    return file_args
    
def DFT(samples):
    lenght = len(samples)
    tab = np.zeros(lenght, dtype=complex)
    tab_indices = np.arange(lenght)
    for i in range(lenght):
        #print(i)
        tab[i] = np.sum(samples * np.exp(-2j * np.pi * i * tab_indices / lenght))
    return tab
    
def search_frequencies(values, N, rate, samples):
    magni = np.abs(values)
    indices = np.argsort(magni)[::-1]
    max_indices = indices[:N]
    max_frequencies = max_indices * (rate / 10) / len(samples)
    return max_frequencies

def analyze_rock():
    if (len(sys.argv) != 4):
        sys.exit(84)
    input_file = check_extension(sys.argv[2])
    if (sys.argv[3].isdigit() == False):
        sys.exit(84)
    Num = (int)(sys.argv[3])
    if (Num == 0):
        sys.exit(84)
    try:
        rate, samples = wavfile.read(input_file)
    except (PermissionError, FileNotFoundError):
        sys.exit(84)
    # print(rate)
    # print(samples)
    if samples.ndim > 1:
        samples = samples.mean(axis=1)
    samples = samples.astype(float)
    too_many_samples = samples[::10]
    values = DFT(too_many_samples)
    max_fr = search_frequencies(values, Num, rate, too_many_samples)
    print(f"Top {Num} frequencies:")
    for i in max_fr:
        print(f"{i:.2f} Hz")
    sys.exit(0)

def verif_file_op(input_file):
    if (os.path.getsize(input_file) == 0):
        sys.exit(84)
    with open(input_file, mode='rb') as f:
        header_status = f.read(44)
        if (header_status[:4] != b'RIFF' or header_status[8:12] != b'WAVE'):
            sys.exit(84)

def open_input_file(input_file, output_file, message):
    try:
        verif_file_op(input_file)
        file = wave.open(input_file, mode='rb')
    except (PermissionError, FileNotFoundError, wave.Error):
        sys.exit(84)
    audio_bytes = bytearray(list(file.readframes(file.getnframes())))
    message += '|STOP|'
    messages_bits = []
    for i in message:
        messages_bits.append(format(ord(i), '08b'))
    #print(messages_bits)
    split_bits_lsb = []
    for i in messages_bits:
        for j in i:
            split_bits_lsb.append((int)(j))
    #print(split_bits_lsb)   
    if (len(split_bits_lsb) > len(audio_bytes)):
        sys.exit(84)
    for i, bit in enumerate(split_bits_lsb):
        audio_bytes[i] = (audio_bytes[i] & ~1) | bit
    try:
        with wave.open(output_file, "wb") as file_modif:
            file_modif.setparams(file.getparams())
            file_modif.writeframes(bytes(audio_bytes))
        file_modif.close()
    except (PermissionError, FileNotFoundError):
        sys.exit(84)
    sys.exit(0)
    
def cypher_rock():
    if (len(sys.argv) != 5):
        sys.exit(84)
    input_file = check_extension(sys.argv[2])
    output_file = check_extension(sys.argv[3])
    message = sys.argv[4]
    for i in message:
        if ((i < 'a' or i > 'z') and (i < 'A' or i > 'Z') and i != " " and (i < '0' or i > '9')):
            sys.exit(84)
    message = message.upper()
    open_input_file(input_file, output_file, message)
    sys.exit(0)

def decypher_rock():
    if (len(sys.argv) != 3):
        sys.exit(84)
    input_file = check_extension(sys.argv[2])
    try:
        verif_file_op(input_file)
        file = wave.open(input_file, mode='rb')
    except (FileNotFoundError, PermissionError, wave.Error):
        sys.exit(84)
    audio_bytes = bytearray(list(file.readframes(file.getnframes())))
    audio_bits = []
    for i in audio_bytes:
        audio_bits.append(str(i & 1))
    #print(audio_bits)
    recover_msg = ""
    for i in range(0, len(audio_bits), 8):
        one_byte = audio_bits[i: i + 8]
        #print(one_byte)
        if (len(one_byte) < 8):
            break
        str_bits = []
        for i in one_byte:
            str_bits.append(str(i))
        one_byte_str = ''.join(str_bits)
        recover_msg += chr(int(one_byte_str, 2))
        if recover_msg.endswith('|STOP|'):
            file.close()
            print(recover_msg[:-6])
            sys.exit(0)
    file.close()
    print(recover_msg)
    sys.exit(0)

def main():
    if (len(sys.argv) == 2 and sys.argv[1] == "--help"):
        print_help()
        sys.exit(0)
    if (len(sys.argv) < 3 or len(sys.argv) > 5):
        sys.exit(84)
    if (sys.argv[1] == "--analyze" or sys.argv[1] == "-a"):
        analyze_rock()
    elif (sys.argv[1] == "--cypher" or sys.argv[1] == "-c"):
        cypher_rock()
    elif (sys.argv[1] == "--decypher" or sys.argv[1] == "-d"):
        decypher_rock()
    else:
        sys.exit(84)
    
if __name__ == '__main__':
    main()